export const Routes = {
  Home: { path: "/dashboard" },
  Dashboard: { path: "/" },
  Loginpage: { path: "/login" },
  signup: { path: "/signup" },
  resetpassword: { path: "/reset-password" },
  resetpasswordconfrim: { path: "/password/reset/:uid/:token" },
  activation: { path: "/activate/:uid/:token" },
  accountList: { path: "/accounts" },
  addAccount: { path: "/account/add/" },
  editAccount: { path: "/account/edit/:id" },
  transactionList: { path: "/transactions" },
  inflowList: { path: "/inflows" },
  outflowList: { path: "/outflows" },
};
